### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'ix'

### ISSUE THREAD

**Issue by Chao8219** [omicsEye/omeClust#1]
It seems that Pandas removed `DataFrame.ix` in the recent release, as one may see in [here](https://stackoverflow.com/questions/59991397/attributeerror-dataframe-object-has-no-attribute-ix).

By installing pandas with a certain version can solve the problem, as suggested in the link.

Best,
Chao

**Comment by GodloveD** [comment]
I will also note that a brand new `pip install` on a fresh system is broken out of the box because of this.  Would be a good idea to fix that imho.  😸

**Comment by grahnavard** [comment]
Thanks, @GodloveD and @Chao8219, for your feedback. The ix issue is fixed. Let us know if you face any issue after your upgrade to the new version.
